### ISSUE TITLE
Problem trying to check ipa consistency in a FreeIPA 4.4.0

### ISSUE THREAD

**Issue by S3nd0h** [peterpakos/ipa_check_consistency#75]
### Actual behaviour
2021-03-04 16:36:27 [main] DEBUG Initialising...
2021-03-04 16:36:27 [main] DEBUG Loading configuration file /home/nagios/.config/checkipaconsistency
2021-03-04 16:36:27 [main] DEBUG DOMAIN = ***.c**l
2021-03-04 16:36:27 [main] DEBUG HOSTS = ds1.***.c**l, ds2.***.c**l, ds3.***.c**l
2021-03-04 16:36:27 [main] DEBUG BINDDN = uid=****,cn=users,cn=accounts,dc=***,dc=c**l
2021-03-04 16:36:27 [main] DEBUG BINDPW = ********
2021-03-04 16:36:27 [main] DEBUG IPA domain: ***.c**l
2021-03-04 16:36:27 [main] DEBUG IPA servers: ds1.***.c**l, ds2.***.c**l, ds3.***.c**l
2021-03-04 16:36:27 [freeipaserver] DEBUG Initialising FreeIPA server ds1.***.c**l
2021-03-04 16:36:27 [freeipaserver] DEBUG Setting up LDAP connection
2021-03-04 16:36:27 [freeipaserver] DEBUG LDAP connection established
2021-03-04 16:36:27 [freeipaserver] DEBUG Grabbing FQDN from LDAP
2021-03-04 16:36:27 [freeipaserver] DEBUG Search base: cn=config, filter: (objectClass=*), attributes: ['nsslapd-localhost'], scope: 0
Traceback (most recent call last):
  File "/usr/local/bin/cipa", line 11, in <module>
    sys.exit(main())
  File "/usr/local/lib/python3.6/site-packages/checkipaconsistency/main.py", line 330, in main
    Main().run()
  File "/usr/local/lib/python3.6/site-packages/checkipaconsistency/main.py", line 118, in __init__
    self._servers[host] = FreeIPAServer(host, self._domain, self._binddn, self._bindpw)
  File "/usr/local/lib/python3.6/site-packages/checkipaconsistency/freeipaserver.py", line 65, in __init__
    self._fqdn = self._get_fqdn()
  File "/usr/local/lib/python3.6/site-packages/checkipaconsistency/freeipaserver.py", line 161, in _get_fqdn
    dn, attrs = results[0]
IndexError: list index out of range

### Steps to reproduce the behaviour
cipa --debug --verbose

### Version of the project
Name: checkipaconsistency
Version: 2.7.10
Summary: Tool to check consistency across FreeIPA servers
Home-page: https://github.com/peterpakos/checkipaconsistency
Author: Peter Pakos
Author-email: peter.pakos@wandisco.com
License: GPLv3
Location: /usr/local/lib/python3.6/site-packages
Requires: prettytable, pplogger, dnspython, python-ldap

### Version of the FreeIPA
4.4.0
### Version of the Operating System
CentOS Linux release 7.4.1708 (Core)

**Comment by schlitzered** [comment]
hey, i created a fork of this projects, you might like to give it a try: https://github.com/schlitzered/checkipaconsistency

**Comment by ishmaelen** [comment]
Same problem, not sorted by schlitzereds fork either.
